apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filebrowser
  name: filebrowser
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          command: ["/filebrowser", "--noauth"]
          volumeMounts:
            - name: workspace-volume
              mountPath: /srv
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: workspace-volume
          hostPath:
            path: /data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
  namespace: default
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the Service
      targetPort: 80  # Port inside the container
      nodePort: 30080 # Port exposed on the node
  type: NodePort
